NOME: Erik Samuel Viana Hsu

TIA: 32265921

NOME: Mateus Kenzo Iochimoto

TIA: 32216289

NOME: Thiago Shihan Cardoso Toma

TIA: 32210744

NOME: Rodrigo Machado de Assis Oliveira de Lima

TIA:32234678

1. (3 pontos). Crie um array NumPy com valores inteiros variando entre 10 e 49. Agora, inverta
o array, usando um único comando NumPy (i.e., o 1o. elemento do array passa a ser o último
e assim por diante).

In [ ]:
import numpy as np
a = np.arange(10, 50)
a_inverso = np.flip(a)

print(a_inverso)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


2. (3 pontos) Considere dois arrays NumPy de mesma dimensão. Confira se eles säo iguais
(usando só um comando).

In [ ]:
import numpy as np

# Arrays de exemplo:

a = [1,2,3,4,5]
b = [1,2,3,4,5]


np.array_equal(a, b)

True

3. (4 pontos) Execute o código em Python a seguir. Explique o resultado obtido.

import numpy as np

a = np.arange(3)

b = np.arange(3)[:, np.newaxis]

print(a)

print(b)

a + b

In [6]:
import numpy as np

a = np.arange(3)

b = np.arange(3)[:, np.newaxis]

print(a)

print(b)

a + b

[0 1 2]
[[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

A variável a guarda um array com 3 elementos, b guarda um array na vertical, juntando a + b, obtemos uma matriz 3x3